import sys
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')

"""
===========================================================================
TRAPPIST-1e Digital Twin -- Stage 2 Extension: VPLanet Integration
===========================================================================

Uses the VPLanet (Virtual Planetary Laboratory Planet Simulator) package
to model long-timescale (100 Myr - 7.6 Gyr) XUV/UV evolution and
atmospheric escape for the TRAPPIST-1 system.

Modules used:
  STELLAR  -- Stellar luminosity and XUV evolution (Barnes+2020)
  FLARE    -- Flare frequency distribution and XUV contribution (Davenport+2019)
  AtmEsc   -- Atmospheric escape driven by XUV bombardment (Barnes+2019)

What VPLanet adds to Stage 2:
  1. Long-timescale cumulative XUV fluence at TRAPPIST-1e (Gyr context)
  2. Fraction of total XUV from flares vs. quiescent stellar emission
  3. Atmospheric escape history: can TRAPPIST-1e retain a secondary N2 atm?
  4. Geological boundary conditions for the photochemical Stage 2 model

What VPLanet does NOT provide (honest limitations):
  - Full 3D atmospheric dynamics (would need CESM/WACCM or Met Office UM)
  - Short-timescale photochemistry (handled by our Chapman+HOx ODE in Stage 2)
  - Transmission spectra (handled by petitRADTRANS in Stage 3)

VPLanet is a 1D planetary evolution code. The 3D atmospheric models from
Chen+2021 (CESM1/WACCM) and Ridgway+2023 (Met Office Unified Model) are
not pip-installable and require dedicated HPC resources.

References:
  Barnes+2020 PASP 132 (VPLanet paper)
  Davenport+2019 ApJ 871 (FFD scaling relations used by FLARE module)
  Barnes+2019 ApJ 871 (AtmEsc XUV escape model)
  Johnstone+2021 A&A (XUV-driven escape for TRAPPIST-1e)
  Bolmont+2017 MNRAS (TRAPPIST-1e habitability evolution)
"""

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import os, tempfile, textwrap, warnings
import vplanet

warnings.filterwarnings('ignore')

OUTPUT_DIR = "Stage 2 Files"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ── TRAPPIST-1 System Parameters ────────────────────────────────────────────
# All from NASA Exoplanet Archive and published literature
STAR = dict(
    mass_msun    = 0.0898,    # Solar masses
    lum_lsun     = 5.22e-4,   # Solar luminosities
    age_gyr      = 7.6,       # Current age (Gyr)
    rot_per_days = 3.30,      # Rotation period
    sat_xuv_frac = 1.0e-3,    # XUV saturation fraction (Lx/Lbol)
    sat_xuv_gyr  = 1.0,       # XUV saturation duration (Gyr)
    xuv_beta     = -1.23,     # XUV power-law decay exponent post-saturation
    flare_E_min_erg = 1e30,   # Minimum flare energy (erg) from Vida+2017
    flare_E_max_erg = 5e33,   # Maximum flare energy (erg)
)

PLANET = dict(
    mass_mearth  = 0.692,     # Earth masses
    radius_rearth= 0.920,     # Earth radii
    semi_au      = 0.02928,   # Semi-major axis (AU)
    ecc          = 0.0,
    # Initial H envelope for escape modelling -- represents a primordial thin
    # secondary atmosphere (0.001 Earth masses ~ 6e21 kg ~ 1% of Earth's atm mass)
    envelope_mass_mearth = 1e-3,
    atm_esc_eff  = 0.15,      # XUV absorption efficiency (Barnes+2019)
)

# Conversion factors
ERG_TO_J = 1e-7
J_TO_ERG  = 1e7
AU_CM = 1.496e13


# ===========================================================================
# SECTION 1: Build VPLanet Input Files
# ===========================================================================
def write_vplanet_inputs(tmpdir, start_age_gyr=0.1, stop_age_gyr=7.6,
                         output_interval_myr=10.0):
    """
    Write VPLanet primary input file and two body files (star + planet)
    into tmpdir. Returns paths to all three files.

    Simulation: TRAPPIST-1 stellar+flare evolution + TRAPPIST-1e atmospheric
    escape from start_age_gyr to stop_age_gyr.

    Unit convention: negative values = use the custom unit shown in docs.
      dMass (star)    : negative = solar masses
      dMass (planet)  : negative = Earth masses
      dSemi           : negative = AU
      dAge            : negative = Gyr
      dLuminosity     : negative = solar luminosities
      dEnvelopeMass   : negative = Earth masses
      dFlareMinEnergy : positive = Joules (SI)
      dFlareMaxEnergy : positive = Joules (SI)
    """
    stop_yr  = stop_age_gyr  * 1e9
    start_yr = start_age_gyr * 1e9
    out_yr   = output_interval_myr * 1e6

    # ── Primary file ────────────────────────────────────────────────────────
    vpl_in = textwrap.dedent(f"""\
        # VPLanet primary input: TRAPPIST-1e Digital Twin
        # Generated by stage2_vplanet_integration.py
        sSystemName   trappist1e_twin
        iVerbose      0
        bOverwrite    1
        saBodyFiles   trappist1_star.in trappist1e_planet.in
        dStopTime     {stop_yr:.3e}       # years ({stop_age_gyr} Gyr)
        dOutputTime   {out_yr:.3e}        # years (every {output_interval_myr:.0f} Myr)
        Units         Years
    """)

    # ── Star: STELLAR + FLARE modules ───────────────────────────────────────
    # Using sFlareFFD DAVENPORT: auto-calibrates FFD from mass and age
    # via Davenport+2019 ApJ 871 scaling relations (calibrated on Kepler M-dwarfs)
    E_min_J = STAR['flare_E_min_erg'] * ERG_TO_J   # 1e23 J
    E_max_J = STAR['flare_E_max_erg'] * ERG_TO_J   # 5e26 J

    star_in = textwrap.dedent(f"""\
        # TRAPPIST-1 stellar input
        sName            trappist1
        saModules        stellar flare
        dMass            -{STAR['mass_msun']}         # Solar masses
        dAge             -{start_age_gyr}             # Gyr (initial simulation age)
        dLuminosity      -{STAR['lum_lsun']}          # Solar luminosities
        dSatXUVFrac      {STAR['sat_xuv_frac']}       # Lx/Lbol saturation (Johnstone+2021)
        dSatXUVTime      -{STAR['sat_xuv_gyr']}       # Gyr saturation duration
        dXUVBeta         {STAR['xuv_beta']}            # Post-saturation power law
        sFlareFFD        DAVENPORT                    # Davenport+2019 FFD scaling
        dFlareMinEnergy  {E_min_J:.3e}                # J (= 1e30 erg, Vida+2017 TRAPPIST-1)
        dFlareMaxEnergy  {E_max_J:.3e}                # J (= 5e33 erg)
        saOutputOrder    Time LXUVFlare LXUVTot LXUVFrac Luminosity RotPer
    """)

    # ── Planet: AtmEsc module ────────────────────────────────────────────────
    # Models XUV-driven atmospheric escape (energy-limited; Barnes+2019)
    planet_in = textwrap.dedent(f"""\
        # TRAPPIST-1e planetary input
        sName            trappist1e
        saModules        atmesc
        dMass            -{PLANET['mass_mearth']}      # Earth masses
        dRadius          -{PLANET['radius_rearth']}    # Earth radii
        dSemi            -{PLANET['semi_au']}          # AU
        dEcc             {PLANET['ecc']}
        dEnvelopeMass    -{PLANET['envelope_mass_mearth']}  # Earth masses (initial H envelope)
        dAtmXAbsEffH     {PLANET['atm_esc_eff']}       # XUV absorption efficiency
        saOutputOrder    Time FXUV EnvelopeMass OxygenMass HEscapeRegime
    """)

    paths = {}
    for fname, content in [('vpl.in', vpl_in),
                            ('trappist1_star.in', star_in),
                            ('trappist1e_planet.in', planet_in)]:
        p = os.path.join(tmpdir, fname)
        with open(p, 'w') as f:
            f.write(content)
        paths[fname] = p

    return paths['vpl.in']


# ===========================================================================
# SECTION 2: Run VPLanet and Parse Output
# ===========================================================================
def run_vplanet_simulation(start_age_gyr=0.1, stop_age_gyr=7.6,
                           output_interval_myr=10.0):
    """
    Execute VPLanet STELLAR+FLARE+AtmEsc simulation for TRAPPIST-1 system.
    Returns (star_df, planet_df) pandas DataFrames with time-series outputs.
    """
    print("\n" + "="*65)
    print("VPLanet: Running STELLAR + FLARE + AtmEsc simulation")
    print("="*65)
    print(f"  System:      TRAPPIST-1 / TRAPPIST-1e")
    print(f"  Time range:  {start_age_gyr} Gyr -- {stop_age_gyr} Gyr")
    print(f"  Output cadence: every {output_interval_myr:.0f} Myr")
    print(f"  Modules:     STELLAR + FLARE (Davenport+2019) + AtmEsc (Barnes+2019)")

    tmpdir = tempfile.mkdtemp(prefix='vplanet_t1e_')
    vpl_path = write_vplanet_inputs(tmpdir, start_age_gyr, stop_age_gyr,
                                    output_interval_myr)

    try:
        out = vplanet.run(vpl_path, quiet=True, units=False)
    except vplanet.VPLANETError as e:
        print(f"  VPLanet run error: {e}")
        print("  Falling back to analytical XUV model (no VPLanet output).")
        return None, None

    # ── Extract star outputs ─────────────────────────────────────────────
    star_body = out.trappist1
    star_data = {}

    for attr in dir(star_body):
        if attr.startswith('_'):
            continue
        try:
            val = getattr(star_body, attr)
            if hasattr(val, '__len__') and len(val) > 1:
                star_data[attr] = np.array(val)
        except Exception:
            pass

    # ── Extract planet outputs ───────────────────────────────────────────
    planet_body = out.trappist1e
    planet_data = {}

    for attr in dir(planet_body):
        if attr.startswith('_'):
            continue
        try:
            val = getattr(planet_body, attr)
            if hasattr(val, '__len__') and len(val) > 1:
                planet_data[attr] = np.array(val)
        except Exception:
            pass

    # Build DataFrames -- coerce all arrays to the same length
    n_star = len(star_data.get('Time', []))
    star_df = pd.DataFrame(
        {k: v[:n_star] for k, v in star_data.items() if len(v) >= n_star}
    ) if star_data else pd.DataFrame()

    n_planet = len(planet_data.get('Time', []))
    planet_df = pd.DataFrame(
        {k: v[:n_planet] for k, v in planet_data.items() if len(v) >= n_planet}
    ) if planet_data else pd.DataFrame()

    # ── Post-process units ───────────────────────────────────────────────
    # Convert time from years to Gyr
    if 'Time' in star_df.columns:
        star_df['Time_Gyr'] = star_df['Time'] / 1e9
    if 'Time' in planet_df.columns:
        planet_df['Time_Gyr'] = planet_df['Time'] / 1e9

    # LXUVFlare and LXUVTot are in Watts in VPLanet output (SI)
    # Convert to erg/s for comparison with Stage 2 literature values
    for col in ['LXUVFlare', 'LXUVTot', 'LXUVFrac', 'Luminosity']:
        if col in star_df.columns:
            # VPLanet returns in SI (Watts); note LXUVFrac is dimensionless
            if col != 'LXUVFrac':
                star_df[f'{col}_ergs'] = star_df[col] * J_TO_ERG
            else:
                star_df[f'{col}_ergs'] = star_df[col]

    # FXUV in planet output: W/m^2 → erg/s/cm^2
    if 'FXUV' in planet_df.columns:
        planet_df['FXUV_ergs_cm2'] = planet_df['FXUV'] * 1e3   # W/m^2 → erg/s/cm^2

    # Cumulative XUV fluence (erg/cm^2) -- integrate FXUV over time
    if 'FXUV_ergs_cm2' in planet_df.columns and 'Time' in planet_df.columns:
        dt_s = np.diff(planet_df['Time'].values) * 365.25 * 86400   # yr → s
        fxuv = planet_df['FXUV_ergs_cm2'].values[:-1]
        planet_df['CumulXUV_ergs_cm2'] = np.append(
            [0.0], np.cumsum(fxuv * dt_s))

    # EnvelopeMass: in kg in VPLanet; convert to Earth masses
    if 'EnvelopeMass' in planet_df.columns:
        M_EARTH_KG = 5.972e24
        planet_df['EnvelopeMass_Mearth'] = planet_df['EnvelopeMass'] / M_EARTH_KG

    print(f"  Star output columns:   {list(star_df.columns[:8])}")
    print(f"  Planet output columns: {list(planet_df.columns[:8])}")
    print(f"  Time steps: {len(star_df)} (star) / {len(planet_df)} (planet)")

    # Save CSVs
    star_df.to_csv(f"{OUTPUT_DIR}/vplanet_star_evolution.csv", index=False)
    planet_df.to_csv(f"{OUTPUT_DIR}/vplanet_planet_evolution.csv", index=False)
    print(f"  Saved: {OUTPUT_DIR}/vplanet_star_evolution.csv")
    print(f"  Saved: {OUTPUT_DIR}/vplanet_planet_evolution.csv")

    return star_df, planet_df


# ===========================================================================
# SECTION 3: Compute Key Derived Quantities
# ===========================================================================
def compute_xuv_context(star_df, planet_df):
    """
    Derive scientifically useful quantities from VPLanet output.
    Returns a summary dict for use in plots and the Stage 2 photochem model.
    """
    ctx = {}

    if star_df is None or len(star_df) == 0:
        print("  No VPLanet star data; computing analytical XUV fallback.")
        return _analytical_xuv_context()

    # ── Current-age values (last row ~ 7.6 Gyr) ─────────────────────────
    final = star_df.iloc[-1]
    ctx['L_xuv_flare_now_ergs']  = final.get('LXUVFlare_ergs', np.nan)
    ctx['L_xuv_total_now_ergs']  = final.get('LXUVTot_ergs', np.nan)
    ctx['L_xuv_frac_now']        = final.get('LXUVFrac', np.nan)
    ctx['lum_now_lsun']          = final.get('Luminosity', np.nan) / 3.828e33 \
                                   if 'Luminosity' in star_df.columns else np.nan

    # ── Flare fraction of XUV at current age ────────────────────────────
    if 'LXUVFlare_ergs' in star_df.columns and 'LXUVTot_ergs' in star_df.columns:
        ctx['flare_xuv_frac_series'] = (star_df['LXUVFlare_ergs'] /
                                        star_df['LXUVTot_ergs'].clip(1e-30))
        ctx['flare_xuv_frac_now'] = float(ctx['flare_xuv_frac_series'].iloc[-1])
    else:
        ctx['flare_xuv_frac_now'] = np.nan

    # ── Cumulative XUV fluence over system lifetime ──────────────────────
    if 'CumulXUV_ergs_cm2' in planet_df.columns:
        ctx['cumul_xuv_fluence_ergs_cm2'] = float(planet_df['CumulXUV_ergs_cm2'].iloc[-1])
        ctx['log10_cumul_xuv'] = np.log10(max(ctx['cumul_xuv_fluence_ergs_cm2'], 1e-30))
    else:
        ctx['cumul_xuv_fluence_ergs_cm2'] = np.nan

    # ── Atmospheric escape summary ───────────────────────────────────────
    if 'EnvelopeMass_Mearth' in planet_df.columns:
        init_mass  = float(planet_df['EnvelopeMass_Mearth'].iloc[0])
        final_mass = float(planet_df['EnvelopeMass_Mearth'].iloc[-1])
        ctx['envelope_init_mearth']   = init_mass
        ctx['envelope_final_mearth']  = final_mass
        ctx['envelope_frac_retained'] = final_mass / max(init_mass, 1e-30)
        ctx['envelope_lost_pct']      = (1 - ctx['envelope_frac_retained']) * 100
    else:
        ctx['envelope_final_mearth']  = np.nan
        ctx['envelope_lost_pct']      = np.nan

    return ctx


def _analytical_xuv_context():
    """
    Fallback: analytical XUV model using Johnstone+2021 / Ribas+2005 scaling.
    Used if VPLanet fails. Provides same interface as compute_xuv_context().
    """
    L_bol_erg = 5.22e-4 * 3.828e33       # erg/s
    # Saturation phase: Lx/Lbol = 1e-3 for ~1 Gyr
    L_xuv_sat  = 1e-3 * L_bol_erg         # erg/s
    # Post-saturation at 7.6 Gyr (power law, beta=-1.23):
    t_sat = 1.0   # Gyr
    t_now = 7.6
    L_xuv_now  = L_xuv_sat * (t_now/t_sat)**(-1.23)

    # Cumulative XUV fluence at TRAPPIST-1e
    a_cm = 0.02928 * 1.496e13
    # Integrate: sat phase (0.1-1 Gyr) + post-sat (1-7.6 Gyr)
    F_sat  = L_xuv_sat  / (4*np.pi*a_cm**2) * 0.9e9 * 3.156e7   # erg/cm^2
    # Post-sat integral of t^-1.23 from 1 to 7.6 Gyr
    beta, t1, t2 = -1.23, 1.0, 7.6
    integral = (t2**(beta+1) - t1**(beta+1)) / (beta+1)  # Gyr^(beta+1)
    F_postsat = (L_xuv_sat / (4*np.pi*a_cm**2)) * integral * 1e9 * 3.156e7
    cumul = F_sat + abs(F_postsat)

    return dict(
        L_xuv_flare_now_ergs  = 0.05 * L_xuv_now,   # ~5% from flares (estimate)
        L_xuv_total_now_ergs  = L_xuv_now,
        L_xuv_frac_now        = L_xuv_now / L_bol_erg,
        lum_now_lsun          = 5.22e-4,
        flare_xuv_frac_now    = 0.05,
        cumul_xuv_fluence_ergs_cm2 = cumul,
        log10_cumul_xuv       = np.log10(cumul),
        envelope_init_mearth  = 1e-3,
        envelope_final_mearth = np.nan,
        envelope_lost_pct     = np.nan,
        note = 'analytical fallback (VPLanet unavailable)'
    )


# ===========================================================================
# SECTION 4: Plots
# ===========================================================================
def plot_vplanet_results(star_df, planet_df, ctx, stage2_uv_df=None):
    """
    Generate a 3-panel figure showing:
      1. XUV luminosity evolution (stellar quiescent + flare contribution)
      2. XUV flux at TRAPPIST-1e + cumulative fluence
      3. Atmospheric escape (envelope mass vs time) + escape regime
    Optionally overlay Stage 2 per-event UV fluences.
    """
    print("\n" + "="*65)
    print("VPLanet: Generating plots")
    print("="*65)

    fig, axes = plt.subplots(1, 3, figsize=(18, 6))
    fig.suptitle(
        "TRAPPIST-1e -- VPLanet Long-Timescale XUV + Atmospheric Escape\n"
        "STELLAR + FLARE (Davenport+2019) + AtmEsc (Barnes+2019) modules",
        fontsize=13, fontweight='bold')

    FALLBACK = (star_df is None or len(star_df) == 0)

    # ── Panel 1: XUV Luminosity Evolution ───────────────────────────────
    ax = axes[0]
    if not FALLBACK and 'Time_Gyr' in star_df.columns:
        t = star_df['Time_Gyr']
        if 'LXUVTot_ergs' in star_df.columns:
            ax.semilogy(t, star_df['LXUVTot_ergs'], 'k-', lw=2,
                        label='L_XUV total (quiescent + flare)')
        if 'LXUVFlare_ergs' in star_df.columns:
            ax.semilogy(t, star_df['LXUVFlare_ergs'], 'r--', lw=1.5,
                        label='L_XUV from flares only')
        if 'Luminosity' in star_df.columns:
            ax.semilogy(t, star_df['Luminosity'] * J_TO_ERG * 1e-4,
                        'b:', lw=1, alpha=0.5, label='L_bol x 1e-4 (scale ref)')
    else:
        # Analytical fallback curve
        t_gyr = np.linspace(0.1, 7.6, 500)
        L_bol = 5.22e-4 * 3.828e33
        L_sat = 1e-3 * L_bol
        L_xuv = np.where(t_gyr < 1.0, L_sat, L_sat * (t_gyr/1.0)**(-1.23))
        ax.semilogy(t_gyr, L_xuv, 'k-', lw=2, label='L_XUV total (analytical)')
        ax.semilogy(t_gyr, 0.05*L_xuv, 'r--', lw=1.5,
                    label='L_XUV flare contribution (~5%)')

    ax.axvline(7.6, color='green', ls=':', lw=1.5, label='Current age 7.6 Gyr')
    ax.axvline(1.0, color='orange', ls=':', lw=1, label='Saturation end ~1 Gyr')
    ax.set_xlabel('Stellar Age (Gyr)')
    ax.set_ylabel('Luminosity (erg/s)')
    ax.set_title('XUV Luminosity Evolution\nSTELLAR + FLARE modules', fontsize=10)
    ax.legend(fontsize=7)
    if not FALLBACK:
        ax.text(0.02, 0.02, 'VPLanet STELLAR+FLARE\nDavenport+2019 FFD',
                transform=ax.transAxes, fontsize=8, va='bottom', color='navy',
                bbox=dict(boxstyle='round', fc='lightcyan', alpha=0.9))
    else:
        ax.text(0.02, 0.02, 'Analytical fallback\n(VPLanet unavailable)',
                transform=ax.transAxes, fontsize=8, va='bottom', color='gray',
                bbox=dict(boxstyle='round', fc='lightyellow', alpha=0.9))

    # ── Panel 2: XUV Flux at Planet + Cumulative Fluence ────────────────
    ax = axes[1]
    if not FALLBACK and 'Time_Gyr' in planet_df.columns:
        t = planet_df['Time_Gyr']
        ax2 = ax.twinx()
        if 'FXUV_ergs_cm2' in planet_df.columns:
            ax.semilogy(t, planet_df['FXUV_ergs_cm2'], 'b-', lw=2,
                        label='F_XUV at TRAPPIST-1e (erg/s/cm^2)')
        if 'CumulXUV_ergs_cm2' in planet_df.columns:
            ax2.semilogy(t, planet_df['CumulXUV_ergs_cm2'].clip(1e10), 'purple',
                         lw=1.5, ls='--', label='Cumulative XUV fluence')
            ax2.set_ylabel('Cumulative XUV Fluence (erg/cm^2)', color='purple',
                           fontsize=8)
            ax2.tick_params(axis='y', colors='purple')
        lines1, labs1 = ax.get_legend_handles_labels()
        lines2, labs2 = ax2.get_legend_handles_labels()
        ax.legend(lines1+lines2, labs1+labs2, fontsize=7)
    else:
        # Analytical fallback
        t_gyr = np.linspace(0.1, 7.6, 500)
        L_sat = 1e-3 * 5.22e-4 * 3.828e33
        L_xuv = np.where(t_gyr < 1.0, L_sat, L_sat * (t_gyr/1.0)**(-1.23))
        a_cm  = 0.02928 * 1.496e13
        F_xuv = L_xuv / (4*np.pi*a_cm**2)
        ax.semilogy(t_gyr, F_xuv, 'b-', lw=2, label='F_XUV at TRAPPIST-1e (analytical)')
        cum = np.cumsum(F_xuv * np.gradient(t_gyr) * 1e9 * 3.156e7)
        ax2 = ax.twinx()
        ax2.semilogy(t_gyr, cum.clip(1e10), 'purple', ls='--', lw=1.5,
                     label='Cumulative XUV (analytical)')
        ax2.set_ylabel('Cumulative XUV Fluence (erg/cm^2)', color='purple', fontsize=8)
        ax2.tick_params(axis='y', colors='purple')
        lines1, labs1 = ax.get_legend_handles_labels()
        lines2, labs2 = ax2.get_legend_handles_labels()
        ax.legend(lines1+lines2, labs1+labs2, fontsize=7)

    # Overlay Stage 2 individual flare UV fluences
    if stage2_uv_df is not None and 'F_NUV_fluence' in stage2_uv_df.columns:
        # Convert flare times in days to Gyr for context overlay
        # They're in the 79-day TESS window -- show as point at current age
        f_nuv = stage2_uv_df['F_NUV_fluence']
        ax.scatter([7.6]*len(f_nuv), f_nuv, c='red', s=20, alpha=0.6,
                   zorder=5, label='TESS flare NUV fluences')

    ax.axvline(7.6, color='green', ls=':', lw=1.5)
    ax.set_xlabel('Stellar Age (Gyr)')
    ax.set_ylabel('XUV Flux at TRAPPIST-1e (erg/s/cm^2)')
    ax.set_title('XUV Flux at TRAPPIST-1e\nAtmEsc module input', fontsize=10)

    if ctx.get('cumul_xuv_fluence_ergs_cm2') and not np.isnan(ctx['cumul_xuv_fluence_ergs_cm2']):
        ax.text(0.02, 0.97, f"Cumul. XUV over 7.6 Gyr:\n"
                f"  {ctx['cumul_xuv_fluence_ergs_cm2']:.2e} erg/cm^2\n"
                f"  log10 = {ctx['log10_cumul_xuv']:.1f}",
                transform=ax.transAxes, fontsize=8, va='top',
                bbox=dict(boxstyle='round', fc='lightyellow', alpha=0.9))

    # ── Panel 3: Atmospheric Escape ──────────────────────────────────────
    ax = axes[2]
    if not FALLBACK and 'Time_Gyr' in planet_df.columns:
        t = planet_df['Time_Gyr']
        if 'EnvelopeMass_Mearth' in planet_df.columns:
            ax.semilogy(t, planet_df['EnvelopeMass_Mearth'].clip(1e-12),
                        'green', lw=2, label='H envelope mass')
            ax.axhline(PLANET['envelope_mass_mearth'], color='k', ls='--', lw=1,
                       label=f'Initial: {PLANET["envelope_mass_mearth"]:.0e} Mearth')
        if 'HEscapeRegime' in planet_df.columns:
            regimes = planet_df['HEscapeRegime']
            ax3 = ax.twinx()
            ax3.plot(t, regimes, 'orange', lw=1, alpha=0.6, label='Escape regime (0=none)')
            ax3.set_ylabel('Escape Regime', color='orange', fontsize=8)
            ax3.tick_params(axis='y', colors='orange')
    else:
        # Analytical escape estimate
        t_gyr  = np.linspace(0.1, 7.6, 500)
        M_init = PLANET['envelope_mass_mearth']
        # Simple mass loss: dM/dt proportional to FXUV
        L_sat  = 1e-3 * 5.22e-4 * 3.828e33
        L_xuv  = np.where(t_gyr < 1.0, L_sat, L_sat * (t_gyr/1.0)**(-1.23))
        a_cm   = 0.02928 * 1.496e13
        F_xuv  = L_xuv / (4*np.pi*a_cm**2)
        # Energy-limited escape: Mdot = eps * pi * R^2 * FXUV / (G*M/R)
        R_p  = 0.920 * 6.371e8          # cm
        M_p  = 0.692 * 5.972e27         # g
        eps  = PLANET['atm_esc_eff']
        G    = 6.674e-8                  # cgs
        Mdot = eps * np.pi * R_p**2 * F_xuv / (G * M_p / R_p)   # g/s
        dt_s = np.gradient(t_gyr) * 1e9 * 3.156e7
        M_lost = np.cumsum(Mdot * dt_s) / 5.972e27               # Mearth
        M_env  = np.maximum(M_init - M_lost, 1e-12)
        ax.semilogy(t_gyr, M_env, 'green', lw=2, label='H envelope (analytical)')
        ax.axhline(M_init, color='k', ls='--', lw=1,
                   label=f'Initial: {M_init:.0e} Mearth')

    ax.axvline(7.6, color='green', ls=':', lw=1.5, label='Current age')
    ax.set_xlabel('Stellar Age (Gyr)')
    ax.set_ylabel('H Envelope Mass (Mearth)')
    ax.set_title('Atmospheric Escape (H envelope)\nAtmEsc module: Barnes+2019', fontsize=10)
    ax.legend(fontsize=7)

    # Summary text box
    summary = (
        f"VPLanet Summary (TRAPPIST-1e):\n"
        f"  Flare XUV fraction:  "
        f"{ctx.get('flare_xuv_frac_now', np.nan):.1%}\n"
        f"  XUV frac (L_XUV/L_bol): "
        f"{ctx.get('L_xuv_frac_now', np.nan):.2e}\n"
        f"  Cumul. XUV (7.6 Gyr): "
        f"{ctx.get('log10_cumul_xuv', np.nan):.1f} erg/cm^2\n"
        f"  H loss: {ctx.get('envelope_lost_pct', np.nan):.1f}%\n"
        f"  Modules: STELLAR+FLARE+AtmEsc\n"
        f"  Note: 1D evolution code\n"
        f"  3D GCM not available"
    )
    axes[0].text(0.02, 0.97, summary, transform=axes[0].transAxes,
                 fontsize=7.5, va='top', family='monospace',
                 bbox=dict(boxstyle='round', fc='lightcyan', ec='navy', alpha=0.9))

    plt.tight_layout()
    path = f"{OUTPUT_DIR}/stage2_vplanet_evolution.png"
    plt.savefig(path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"  Saved: {path}")
    return path


# ===========================================================================
# SECTION 5: Main
# ===========================================================================
if __name__ == "__main__":
    print("\n" + "#"*65)
    print("  TRAPPIST-1e -- STAGE 2 VPLANET INTEGRATION")
    print("#"*65 + "\n")

    # Load Stage 2 UV data if available (for overlay on Panel 2)
    uv_df = None
    uv_path = f"{OUTPUT_DIR}/flare_uv_enhancement.csv"
    if os.path.exists(uv_path):
        uv_df = pd.read_csv(uv_path)
        print(f"  Loaded Stage 2 UV enhancement data: {len(uv_df)} flares")
    else:
        print("  Stage 2 UV data not found. Run stage2_atmospheric_response.py first.")

    # Run VPLanet simulation
    star_df, planet_df = run_vplanet_simulation(
        start_age_gyr=0.1,
        stop_age_gyr=7.6,
        output_interval_myr=10.0
    )

    # Compute derived context
    ctx = compute_xuv_context(star_df, planet_df)

    print("\n" + "="*65)
    print("VPLanet: Key Results")
    print("="*65)
    print(f"  Flare XUV fraction at 7.6 Gyr: {ctx.get('flare_xuv_frac_now', 'N/A')}")
    if not np.isnan(ctx.get('cumul_xuv_fluence_ergs_cm2', np.nan)):
        print(f"  Cumulative XUV fluence (full age): "
              f"{ctx['cumul_xuv_fluence_ergs_cm2']:.2e} erg/cm^2  "
              f"(log10 = {ctx['log10_cumul_xuv']:.1f})")
    if not np.isnan(ctx.get('envelope_lost_pct', np.nan)):
        print(f"  H envelope lost: {ctx['envelope_lost_pct']:.1f}%")
        if ctx['envelope_lost_pct'] > 90:
            print("  Conclusion: primordial H envelope fully stripped.")
            print("  TRAPPIST-1e could only retain a secondary (N2/CO2) atmosphere.")
        else:
            print("  Conclusion: partial envelope retention possible.")

    print("\n" + "="*65)
    print("VPLanet: 1D vs 3D Model Limitations")
    print("="*65)
    print("""
  VPLanet provides:
    - 1D stellar+planetary evolution (Myr-Gyr timescales)
    - Validated XUV luminosity models (Barnes+2020, Johnstone+2021)
    - Energy-limited atmospheric escape (Barnes+2019)
    - Flare XUV contribution via Davenport+2019 FFD

  VPLanet does NOT provide:
    - 3D atmospheric dynamics or general circulation
    - Atmospheric photochemistry (handled by our Chapman+HOx ODE)
    - Transmission spectra (handled by petitRADTRANS in Stage 3)

  True 3D models (Chen+2021 CESM/WACCM; Ridgway+2023 Met Office UM):
    - Find O3 can INCREASE 20x during flares (opposite of 1D predictions)
    - Require dedicated HPC clusters; not pip-installable
    - Represent an open research question, not a solved problem
    - Are documented as a known limitation in this digital twin

  This implementation is scientifically defensible at 1D fidelity
  with VPLanet providing the geological-timescale XUV context.
""")

    # Generate plots
    plot_vplanet_results(star_df, planet_df, ctx, stage2_uv_df=uv_df)

    print("\n" + "="*65)
    print("VPLANET INTEGRATION COMPLETE")
    print("="*65)
    print(f"""
  Output files: {OUTPUT_DIR}/
    vplanet_star_evolution.csv
    vplanet_planet_evolution.csv
    stage2_vplanet_evolution.png

  -> Stage 2 is now augmented with VPLanet STELLAR+FLARE+AtmEsc
  -> Ready for Stage 3: petitRADTRANS spectral generation
""")
